Controllers/ItemsController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using StoreManagementSystem.Data;
using StoreManagementSystem.Models;

namespace StoreManagementSystem.Controllers
{
    public class ItemsController : Controller
    {
        private readonly StoreManagementSystemContext _context;

        public ItemsController(StoreManagementSystemContext context)
        {
            _context = context;
        }

        // GET: Items
        public async Task<IActionResult> Index()
        {
            var itemQuery = _context.Items.Include(i => i.Category).Include(i => i.Unit);

            return View(await itemQuery.ToListAsync());
        }

        // GET: Items/Details/5
        public async Task<IActionResult> Details(long? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var item = await _context.Items
                .Include(i => i.Category)
                .Include(i => i.Unit)
                .FirstOrDefaultAsync(m => m.Id == id);

            if (item == null)
            {
                return NotFound();
            }

            return View(item);
        }

        // GET: Items/Create
        public IActionResult Create()
        {

            ViewData["CategoryId"] = new SelectList(_context.ItemCategories, "Id", "Name");
            ViewData["UnitId"] = new SelectList(_context.Units, "Id", "Symbol");

            return View();
        }

        // POST: Items/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("CategoryId,UnitId,Description,Ref,GroupCode")] Item item)
        {
            if (ModelState.IsValid)
            {
                item.CreatedOn = DateTime.UtcNow;
                item.UpdatedOn = DateTime.UtcNow;

                _context.Add(item);

                await _context.SaveChangesAsync();


                var category = await _context.ItemCategories.FindAsync(item.CategoryId);

                item.GroupCode = "00000" + item.Id.ToString() + category.GroupCode;

                _context.Update(item);

                await _context.SaveChangesAsync();

                return RedirectToAction(nameof(Index));
            }

            ViewData["CategoryId"] = new SelectList(_context.ItemCategories, "Id", "Name", item.CategoryId);
            ViewData["UnitId"] = new SelectList(_context.Units, "Id", "Symbol", item.UnitId);

            return View(item);
        }

        // GET: Items/Edit/5
        public async Task<IActionResult> Edit(long? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var item = await _context.Items.FindAsync(id);
            if (item == null)
            {
                return NotFound();
            }

            ViewData["CategoryId"] = new SelectList(_context.ItemCategories, "Id", "Name", item.CategoryId);
            ViewData["UnitId"] = new SelectList(_context.Units, "Id", "Symbol", item.UnitId);

            return View(item);
        }

        // POST: Items/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(long id, [Bind("CategoryId,UnitId,Description,GroupCode,Ref,Id")] Item item)
        {
            if (id != item.Id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    var oldItem = await _context.Items.AsNoTracking().FirstOrDefaultAsync( i => i.Id == item.Id);

                    var category = await _context.ItemCategories.FindAsync(item.CategoryId);

                    item.GroupCode = "00000" + item.Id.ToString() + category.GroupCode;

                    item.UpdatedOn = DateTime.UtcNow;
                    item.CreatedOn = oldItem.CreatedOn;

                    _context.Update(item);

                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!ItemExists(item.Id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }

            ViewData["CategoryId"] = new SelectList(_context.ItemCategories, "Id", "Name", item.CategoryId);
            ViewData["UnitId"] = new SelectList(_context.Units, "Id", "Symbol", item.UnitId);

            return View(item);
        }

        // GET: Items/Delete/5
        public async Task<IActionResult> Delete(long? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var item = await _context.Items
                .Include(i => i.Category)
                .Include(i => i.Unit)
                .FirstOrDefaultAsync(m => m.Id == id);

            if (item == null)
            {
                return NotFound();
            }

            return View(item);
        }

        // POST: Items/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(long id)
        {
            var item = await _context.Items.FindAsync(id);
            if (item != null)
            {
                _context.Items.Remove(item);
            }

            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool ItemExists(long id)
        {
            return _context.Items.Any(e => e.Id == id);
        }
    }
}

Controllers/RequisitionsController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using StoreManagementSystem.Data;
using StoreManagementSystem.Models;

namespace StoreManagementSystem.Controllers
{
    public class RequisitionsController : Controller
    {
        private readonly StoreManagementSystemContext _context;

        public RequisitionsController(StoreManagementSystemContext context)
        {
            _context = context;
        }

        // GET: Requisitions
        public async Task<IActionResult> Index()
        {
            return View(await _context.Requisitions.ToListAsync());
        }

        // GET: Requisitions/Details/5
        public async Task<IActionResult> Details(long? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var requisition = await _context.Requisitions
                        .Include( r => r.RequisitionItems)
                            .ThenInclude( ri => ri.Item)
                                .ThenInclude(i => i.Unit)

                        .FirstOrDefaultAsync(m => m.Id == id);

            if (requisition == null)
            {
                return NotFound();
            }

            return View(requisition);
        }

        // GET: Requisitions/Create
        public async Task<IActionResult> Create()
        {

            var items = await _context.Items.ToListAsync();

            ViewData["items"] = items;

            return View();
        }

        // POST: Requisitions/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("Number,Status,RefNumber,CreatedOn,RequisitionItems")] Requisition requisition)
        {
            if (ModelState.IsValid)
            {

                requisition.CreatedOn = DateTime.UtcNow;
                requisition.UpdatedOn = DateTime.UtcNow;

                string uniqueNumber = DateTime.UtcNow.ToString("yyMdHms");

                requisition.Number = uniqueNumber;

                _context.Add(requisition);
                await _context.SaveChangesAsync();

                return RedirectToAction(nameof(Index));
            }

            return View(requisition);
        }

        // GET: Requisitions/Edit/5
        public async Task<IActionResult> Edit(long? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var items = await _context.Items.ToListAsync();

            var requisition = await _context.Requisitions.Include(r => r.RequisitionItems).SingleOrDefaultAsync(r => r.Id == id);

            if (requisition == null)
            {
                return NotFound();
            }

            ViewData["items"] = items;

            return View(requisition);
        }

        // POST: Requisitions/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(long id, [Bind("Number,Status,RefNumber,Id,RequisitionItems")] Requisition requisition)
        {
            if (id != requisition.Id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {

                    var oldRequisition = await _context.Requisitions.AsNoTracking().SingleOrDefaultAsync(r => r.Id == requisition.Id);

                    requisition.CreatedOn = oldRequisition.CreatedOn;
                    requisition.Number = oldRequisition.Number;
                    requisition.Status = oldRequisition.Status;
                    requisition.UpdatedOn = DateTime.UtcNow;

                    _context.Update(requisition);

                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!RequisitionExists(requisition.Id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(requisition);
        }

        // GET: Requisitions/Delete/5
        public async Task<IActionResult> Delete(long? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var requisition = await _context.Requisitions
                .FirstOrDefaultAsync(m => m.Id == id);
            if (requisition == null)
            {
                return NotFound();
            }

            return View(requisition);
        }

        // POST: Requisitions/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(long id)
        {
            var requisition = await _context.Requisitions.FindAsync(id);
            if (requisition != null)
            {
                _context.Requisitions.Remove(requisition);
            }

            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool RequisitionExists(long id)
        {
            return _context.Requisitions.Any(e => e.Id == id);
        }
    }
}

Controllers/UnitsController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using StoreManagementSystem.Data;
using StoreManagementSystem.Models;

namespace StoreManagementSystem.Controllers
{
    public class UnitsController : Controller
    {
        private readonly StoreManagementSystemContext _context;

        public UnitsController(StoreManagementSystemContext context)
        {
            _context = context;
        }

        // GET: Units
        public async Task<IActionResult> Index()
        {
            return View(await _context.Units.ToListAsync());
        }


        // GET: Units/Create
        public IActionResult Create()
        {
            return View();
        }

        // POST: Units/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("Symbol,Name")] Unit unit)
        {
            if (ModelState.IsValid)
            {
                unit.CreatedOn = DateTime.UtcNow;
                unit.UpdatedOn = DateTime.UtcNow;

                _context.Add(unit);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            return View(unit);
        }

        // GET: Units/Edit/5
        public async Task<IActionResult> Edit(long? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var unit = await _context.Units.FindAsync(id);

            if (unit == null)
            {
                return NotFound();
            }
            return View(unit);
        }

        // POST: Units/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(long id, [Bind("Symbol,Name,Id")] Unit unit)
        {
            if (id != unit.Id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    var oldUnit = await _context.Units.AsNoTracking().SingleOrDefaultAsync(u => u.Id == unit.Id);

                    unit.UpdatedOn = DateTime.UtcNow;
                    unit.CreatedOn = oldUnit.CreatedOn;

                    _context.Update(unit);

                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!UnitExists(unit.Id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(unit);
        }

        // GET: Units/Delete/5
        public async Task<IActionResult> Delete(long? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var unit = await _context.Units
                .FirstOrDefaultAsync(m => m.Id == id);

            if (unit == null)
            {
                return NotFound();
            }

            return View(unit);
        }

        // POST: Units/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(long id)
        {
            var unit = await _context.Units.FindAsync(id);
            if (unit != null)
            {
                _context.Units.Remove(unit);
            }

            await _context.SaveChangesAsync();

            return RedirectToAction(nameof(Index));
        }

        private bool UnitExists(long id)
        {
            return _context.Units.Any(e => e.Id == id);
        }

    }
}

Views/Partial/_Breadcum.cshtml
@if (ViewData["isBreadcumNotVisible"] == null)
{
    <div class="content-header">
        <div class="container-fluid">
            <div class="row mb-0">
                <div class="col-sm-6">
                    <h4 class="m-0 text-dark">
                        @if (ViewData["page_name"] != null)
                        {
                            @ViewData["page_name"]
                        }
                    </h4>
                </div><!-- /.col -->
                <div class="col-sm-6">
                    <ol class="breadcrumb float-sm-right">
                        <li class="breadcrumb-item"><a href="/">Home</a></li>
                        <li class="breadcrumb-item active">
                            @if (ViewData["page_name"] != null)
                            {
                                @ViewData["page_name"]
                            }
                        </li>
                    </ol>
                </div><!-- /.col -->
            </div><!-- /.row -->
        </div><!-- /.container-fluid -->
    </div>
}

Views/Partial/_Footer.cshtml
     <footer class="main-footer text-sm">
        <strong>Copyright &copy; 2020 <a href="http://azimandson.com">Azim & Son (PVT) Ltd</a>.</strong>
        All rights reserved.
        <div class="float-right d-none d-sm-inline-block">
        </div>
      </footer>

Views/Partial/_Header.cshtml
<nav class="main-header navbar navbar-expand navbar-light text-sm">
    <!-- Left navbar links -->
    <ul class="navbar-nav">
        <li class="nav-item">
            <a class="nav-link" data-widget="pushmenu" href="#" role="button"><i class="fas fa-bars"></i></a>
        </li>
        <li class="nav-item d-none d-sm-inline-block">
            <a href="/" class="nav-link">Home</a>
        </li>
    </ul>

    <!-- SEARCH FORM -->
    <form class="form-inline ml-3">
        <div class="input-group input-group-sm">
            <input class="form-control form-control-navbar" type="search" placeholder="Search" aria-label="Search">
            <div class="input-group-append">
                <button class="btn btn-navbar" type="submit">
                    <i class="fas fa-search"></i>
                </button>
            </div>
        </div>
    </form>

    <!-- Right navbar links -->
    <ul class="navbar-nav ml-auto">
        <!-- Notifications Dropdown Menu -->

        @* <li class="nav-item dropdown">
            <a class="nav-link dropdown-toggle" data-bs-toggle="dropdown" href="#">
                User Name
            </a>
            <div class="dropdown-menu dropstart">

                <a href="#" class="dropdown-item dropdown-footer" id="logout-button">Logout</a>

                <form asp-area="Organization" asp-controller="Auth" asp-action="Logout" method="POST" id="logout-form">
                </form>

            </div>
        </li> *@

    </ul>
</nav>

Views/Partial/_Sidebar.cshtml
<aside class="main-sidebar elevation-4 sidebar-light-navy">
    <!-- Brand Logo -->
    <a href="/" class="brand-link">
        <span class="brand-text text-sm">Store Name</span>
    </a>

    <!-- Sidebar -->
    <div class="sidebar">
        <!-- Sidebar user panel (optional) -->
        <div class="user-panel mt-3 pb-3 mb-3 d-flex">
            <div class="image">
                <img src="/img/avatar5.png" class="img-circle elevation-2" alt="User Image">
            </div>
            <div class="info">
                <a asp-area="Organization" asp-controller="UserProfile" asp-action="Index" class="d-block"> </a>
            </div>
        </div>

        <!-- Sidebar Menu -->
        <nav class="mt-2">
            <ul class="nav nav-pills nav-sidebar flex-column nav-compact nav-child-indent nav-collapse-hide-child nav-flat" data-widget="treeview" role="menu"
                data-accordion="false">


                <li class="nav-item has-treeview @(ViewData["open_menu"]?.ToString() == "item_setup" ? "menu-open": "") ">
                    <a href="#" class="nav-link @(ViewData["open_menu"]?.ToString() == "item_setup" ? "active": "")">
                            <i class="fa fa-cog"></i>
                            <p>
                                Item Setup
                                <i class="fas fa-angle-left right"></i>
                            </p>
                        </a>
                        <ul class="nav nav-treeview">

                            <li class="nav-item">
                                <a asp-controller="Units" asp-action="Index" class="nav-link @(ViewData["active_option"]?.ToString() == "unit_list" ? "active": "")">
                                <i class="fa fa-table nav-icon"></i>
                                    <p>Unit</p>
                                </a>
                            </li>

                            <li class="nav-item">
                                <a asp-controller="ItemCategories" asp-action="Index" class="nav-link @(ViewData["active_option"]?.ToString() == "category_list" ? "active": "")">
                                    <i class="fa fa-table nav-icon"></i>
                                    <p>Item Category </p>
                                </a>
                            </li>

                            <li class="nav-item">
                                <a asp-controller="Items" asp-action="Index" class="nav-link @(ViewData["active_option"]?.ToString() == "item_list" ? "active": "")">
                                    <i class="fa fa-table nav-icon"></i>
                                    <p>Item</p>
                                </a>
                            </li>


                        </ul>
                    </li>

                    <li class="nav-item has-treeview @(ViewData["open_menu"]?.ToString() == "requisition" ? "menu-open": "") ">
                    <a href="#" class="nav-link @(ViewData["open_menu"]?.ToString() == "requisition" ? "active": "")">
                        <i class="fa fa-registered"></i>
                            <p>
                                Requisition
                                <i class="fas fa-angle-left right"></i>
                            </p>
                        </a>
                        <ul class="nav nav-treeview">

                            <li class="nav-item">
                            <a asp-controller="Requisitions" asp-action="Create" class="nav-link @(ViewData["active_option"]?.ToString() == "requisition_create" ? "active": "")">
                                    <i class="fa fa-table nav-icon"></i>
                                    <p>Create</p>
                                </a>
                            </li>

                            <li class="nav-item">
                            <a asp-controller="Requisitions" asp-action="Index" class="nav-link @(ViewData["active_option"]?.ToString() == "requisition_list" ? "active": "")">
                                    <i class="fa fa-table nav-icon"></i>
                                    <p>List</p>
                                </a>
                            </li>


                        </ul>
                    </li>
                


            </ul>
        </nav>
        <!-- /.sidebar-menu -->
    </div>
    <!-- /.sidebar -->
</aside>